03-20 10:30:28 jdbc[16]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT PRODUCT_SEQ.NEXTVAL UNION[*] SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL "; expected "identifier"; SQL statement:
select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval [42001-175]
03-20 10:31:42 jdbc[25]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT PRODUCT_SEQ.NEXTVAL UNION[*] SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL UNION SELECT PRODUCT_SEQ.NEXTVAL "; expected "identifier"; SQL statement:
select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval union select product_seq.nextval [42001-175]
03-20 10:35:32 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT CUSTOMER_SEQ.NEXTVAL UNION[*] SELECT CUSTOMER_SEQ.NEXTVAL UNION SELECT CUSTOMER_SEQ.NEXTVAL UNION SELECT CUSTOMER_SEQ.NEXTVAL UNION SELECT CUSTOMER_SEQ.NEXTVAL UNION SELECT CUSTOMER_SEQ.NEXTVAL UNION SELECT CUSTOMER_SEQ.NEXTVAL UNION SELECT CUSTOMER_SEQ.NEXTVAL UNION SELECT CUSTOMER_SEQ.NEXTVAL UNION SELECT CUSTOMER_SEQ.NEXTVAL UNION SELECT CUSTOMER_SEQ.NEXTVAL UNION SELECT CUSTOMER_SEQ.NEXTVAL UNION SELECT CUSTOMER_SEQ.NEXTVAL UNION SELECT CUSTOMER_SEQ.NEXTVAL UNION SELECT CUSTOMER_SEQ.NEXTVAL UNION SELECT CUSTOMER_SEQ.NEXTVAL UNION SELECT CUSTOMER_SEQ.NEXTVAL UNION SELECT CUSTOMER_SEQ.NEXTVAL UNION SELECT CUSTOMER_SEQ.NEXTVAL UNION SELECT CUSTOMER_SEQ.NEXTVAL "; expected "identifier"; SQL statement:
select customer_seq.nextval union select customer_seq.nextval union select customer_seq.nextval union select customer_seq.nextval union select customer_seq.nextval union select customer_seq.nextval union select customer_seq.nextval union select customer_seq.nextval union select customer_seq.nextval union select customer_seq.nextval union select customer_seq.nextval union select customer_seq.nextval union select customer_seq.nextval union select customer_seq.nextval union select customer_seq.nextval union select customer_seq.nextval union select customer_seq.nextval union select customer_seq.nextval union select customer_seq.nextval union select customer_seq.nextval [42001-175]
03-20 13:35:32 jdbc[114]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:351)
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238)
	at scala.collection.immutable.List.map(List.scala:274)
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:90)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130)
	at scala.Option.map(Option.scala:145)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128)
	at scala.util.Success.flatMap(Try.scala:230)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 39 more
03-20 13:35:32 jdbc[114]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:351)
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238)
	at scala.collection.immutable.List.map(List.scala:274)
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:90)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130)
	at scala.Option.map(Option.scala:145)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128)
	at scala.util.Success.flatMap(Try.scala:230)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 39 more
03-20 13:51:32 jdbc[122]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:351)
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238)
	at scala.collection.immutable.List.map(List.scala:274)
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:90)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130)
	at scala.Option.map(Option.scala:145)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128)
	at scala.util.Success.flatMap(Try.scala:230)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 39 more
03-20 15:05:55 jdbc[183]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:656)
	at org.h2.server.web.WebApp.login(WebApp.java:905)
	at org.h2.server.web.WebApp.process(WebApp.java:209)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:168)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Thread.java:745)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:351)
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238)
	at scala.collection.immutable.List.map(List.scala:274)
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:90)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130)
	at scala.Option.map(Option.scala:145)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128)
	at scala.util.Success.flatMap(Try.scala:230)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 39 more
03-23 12:40:02 jdbc[11]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT CONTACT_SEQ.NEXTVAL UNION[*] SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL "; expected "identifier"; SQL statement:
select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval [42001-175]
03-23 12:45:04 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Column "T0.CUST_EMAIL" not found; SQL statement:
select t0.contact_id c0, t0.cust_email c1, t0.topic c2, t0.query c3, t0.date_created c4, t0.status c5 from contact t0 [42122-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.expression.Alias.optimize(Alias.java:52)
	at org.h2.command.dml.Select.prepare(Select.java:810)
	at org.h2.command.Parser.prepareCommand(Parser.java:240)
	at org.h2.engine.Session.prepareLocal(Session.java:436)
	at org.h2.engine.Session.prepareCommand(Session.java:379)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at com.jolbox.bonecp.ConnectionHandle.prepareStatement(ConnectionHandle.java:1024)
	at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQueryWithOption(CQuery.java:391)
	at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQuery(CQuery.java:368)
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:165)
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:77)
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:263)
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1502)
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:890)
	at play.db.ebean.Model$Finder.all(Model.java:258)
	at models.Contact.findAll(Contact.java:32)
	at controllers.ManagementController.contactList(ManagementController.java:47)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$30$$anonfun$apply$30.apply(routes_routing.scala:508)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$30$$anonfun$apply$30.apply(routes_routing.scala:508)
	at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264)
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55)
	at play.mvc.Security$AuthenticatedAction.call(Security.java:44)
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:492)
	at play.core.j.JavaAction$class.apply(JavaAction.scala:82)
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
	at scala.Option.map(Option.scala:145)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
03-23 12:46:37 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Column "CUST_ID" not found; SQL statement:
create table Contact
(
contact_id number,
cust_email number,
topic varchar2(255),
query varchar2(4000),
date_created timestamp,
status varchar2(255)check (status in ('Open','Closed')),
Primary Key(contact_id),
Foreign Key(cust_id)references Customer(cust_id)on delete cascade
) [42122-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.table.Table.getColumn(Table.java:626)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:75)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:188)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:70)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:169)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:181)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1321)
	at org.h2.server.web.WebApp.query(WebApp.java:1010)
	at org.h2.server.web.WebApp$1.next(WebApp.java:972)
	at org.h2.server.web.WebApp$1.next(WebApp.java:959)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Thread.java:745)
03-23 12:47:28 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT CONTACT_SEQ.NEXTVAL UNION[*] SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL UNION SELECT CONTACT_SEQ.NEXTVAL "; expected "identifier"; SQL statement:
select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval union select contact_seq.nextval [42001-175]
03-23 12:48:06 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'deanflood1991@hotmail.com' (CONTACT: CUST_EMAIL NUMBER)"; SQL statement:
insert into contact (contact_id, cust_email, topic, query, date_created, status) values (?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6) [22018-175]
03-27 11:40:24 jdbc[41]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT TRANSACTIONS_SEQ.NEXTVAL UNION[*] SELECT TRANSACTIONS_SEQ.NEXTVAL UNION SELECT TRANSACTIONS_SEQ.NEXTVAL UNION SELECT TRANSACTIONS_SEQ.NEXTVAL UNION SELECT TRANSACTIONS_SEQ.NEXTVAL UNION SELECT TRANSACTIONS_SEQ.NEXTVAL UNION SELECT TRANSACTIONS_SEQ.NEXTVAL UNION SELECT TRANSACTIONS_SEQ.NEXTVAL UNION SELECT TRANSACTIONS_SEQ.NEXTVAL UNION SELECT TRANSACTIONS_SEQ.NEXTVAL UNION SELECT TRANSACTIONS_SEQ.NEXTVAL UNION SELECT TRANSACTIONS_SEQ.NEXTVAL UNION SELECT TRANSACTIONS_SEQ.NEXTVAL UNION SELECT TRANSACTIONS_SEQ.NEXTVAL UNION SELECT TRANSACTIONS_SEQ.NEXTVAL UNION SELECT TRANSACTIONS_SEQ.NEXTVAL UNION SELECT TRANSACTIONS_SEQ.NEXTVAL UNION SELECT TRANSACTIONS_SEQ.NEXTVAL UNION SELECT TRANSACTIONS_SEQ.NEXTVAL UNION SELECT TRANSACTIONS_SEQ.NEXTVAL "; expected "identifier"; SQL statement:
select transactions_seq.nextval union select transactions_seq.nextval union select transactions_seq.nextval union select transactions_seq.nextval union select transactions_seq.nextval union select transactions_seq.nextval union select transactions_seq.nextval union select transactions_seq.nextval union select transactions_seq.nextval union select transactions_seq.nextval union select transactions_seq.nextval union select transactions_seq.nextval union select transactions_seq.nextval union select transactions_seq.nextval union select transactions_seq.nextval union select transactions_seq.nextval union select transactions_seq.nextval union select transactions_seq.nextval union select transactions_seq.nextval union select transactions_seq.nextval [42001-175]
03-27 13:53:35 jdbc[82]: exception
org.h2.jdbc.JdbcSQLException: Sequence "TRANSACTION_SEQ" not found; SQL statement:
drop sequence transaction_seq [90036-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.command.ddl.DropSequence.update(DropSequence.java:46)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:181)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1321)
	at org.h2.server.web.WebApp.query(WebApp.java:1010)
	at org.h2.server.web.WebApp$1.next(WebApp.java:972)
	at org.h2.server.web.WebApp$1.next(WebApp.java:959)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Thread.java:745)
03-27 13:54:08 jdbc[82]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE TRANSACTIONS_SEQ
START[*] WITH 1
INCREMENT BY 1 "; SQL statement:
create table transactions_seq
start with 1
increment by 1 [42000-175]
03-27 13:54:11 jdbc[82]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE TRANSACTIONS_SEQ
START[*] WITH 1
INCREMENT BY 1 "; SQL statement:
create table transactions_seq
start with 1
increment by 1 [42000-175]
03-27 14:09:10 jdbc[109]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:351)
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238)
	at scala.collection.immutable.List.map(List.scala:274)
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:90)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130)
	at scala.Option.map(Option.scala:145)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128)
	at scala.util.Success.flatMap(Try.scala:230)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 39 more
03-27 14:09:10 jdbc[109]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:351)
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238)
	at scala.collection.immutable.List.map(List.scala:274)
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:90)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130)
	at scala.Option.map(Option.scala:145)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128)
	at scala.util.Success.flatMap(Try.scala:230)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 39 more
